version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx_service
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - wordpress_file:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_service
    container_name: wordpress_container
    volumes:
      - wordpress_file:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_service
    container_name: mariadb_container
    volumes:
      - mariadb_file:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress_file:
  mariadb_file:

networks:
  inception: