FROM debian:buster

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    wget \
    curl \
    nginx \
    php7.3-fpm \
    php7.3-mysql \
    php7.3-mbstring \
    php7.3-xml \
    php7.3-gd \
    php7.3-curl \
    php7.3-zip \
    && rm -rf /var/lib/apt/lists/*

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

RUN wget https://wordpress.org/latest.tar.gz \
    && tar -xvf latest.tar.gz \
    && rm latest.tar.gz \
    && mv wordpress /var/www/html/wordpress \
    && chown -R www-data:www-data /var/www/html/wordpress \
    && chmod -R 755 /var/www/html/wordpress

COPY ./conf/wordpress.conf /etc/php/7.3/fpm/pool.d/wordpress.conf
COPY ./conf/configure.sh /conf/configure.sh

RUN chmod +x /conf/configure.sh
RUN mkdir -p /run/php

EXPOSE 9000

ENTRYPOINT ["/conf/configure.sh"]
