FROM debian:buster

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    wget \
    nginx \
    php7.3-fpm \
    php7.3-mysql \
    php7.3-mbstring \
    php7.3-xml \
    php7.3-gd \
    php7.3-curl \
    php7.3-zip \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://wordpress.org/latest.tar.gz \
    && tar -xvf latest.tar.gz \
    && rm latest.tar.gz \
    && mv wordpress /var/www/html/wordpress \
    && chown -R www-data:www-data /var/www/html/wordpress \
    && chmod -R 755 /var/www/html/wordpress

COPY ./conf/wordpress.conf /etc/php/7.3/fpm/pool.d/wordpress.conf
COPY ./conf/wp-config.php /var/www/html/wordpress/wp-config.php

RUN mkdir -p /run/php

EXPOSE 9000

CMD ["php-fpm7.3", "-F"]